on:
  push:
    branches:
      - feat/*

jobs:
  build:
    name: CI Pipeline
    runs-on:
      group: Default
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - uses: actions/checkout@v4
        with:
          repository: SOXAM/yliad-web
      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies, test and build
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: create deploy.zip
        run: zip -r deploy.zip .

      # Deploy
      - name: deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
          application_name: yliad
          environment_name: develop
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{github.SHA}}
          deployment_package: deploy.zip
          use_existing_version_if_available: true